# Generated by Django 3.2.9 on 2021-11-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technology', 'technology'), ('health', 'health'), ('economy', 'economy'), ('science', 'science')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_post', models.CharField(max_length=155)),
            ],
        ),
    ]
